remote_theme: ramiropolla/jekyll-smart-material

title: techne gratia artis
description: descriptionbla

github_username: ramiropolla
email: ramiro.polla@gmail.com

minima:
  date_format: "%Y-%m-%d"

baseurl: ""
url: "http://ramiropolla.github.io"
