# Site settings
title: Smart Material Theme
description: Slick Material Design theme for Jekyll powered by Material Design Lite.

# Custom theme could be generated at: https://getmdl.io/customize/index.html
material_theme: blue-deep_orange
